export { default as Main } from './Main';
export { default as CardList } from './CardList';
export { default as Header } from './Header';
export { default as AddAlbum } from './AddAlbum';
export { default as Card } from './Card';
export { default as Like } from './Like';
export { default as Api } from './Lyrics_Api';
export { default as BackButton } from './BackButton';
export { default as Nav } from './Nav';
